package projectEuler;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
//        0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

import java.util.Scanner;

public class EvenFibonacciNumbers {
    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        System.out.println("Podaj liczbę w ciągu Fibonacciego");
        long n = scanner.nextInt();
        System.out.println(fibonacciResult(n));

    }

    private static long fibonacciResult(long n) {
        long f0 = 0;
        long f1 = 1;
        long result = 0;

        for (int i = 0; i < n; i++) {
            if (n == 0) {
                result = f0;
            } else if (n == 1) {
                result = f1;
            } else if (n >= 2) {
                f0 = f1;
                f1 = result;
                result = f0 + f1;
            }
        }
        return result;
    }
}
