package inneRozwiazania_powtorka;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

//answer: 4613732

public class EvenFibonacciNumbers {

	public static void main(String[] args) {

		int f1 = 1;
		int f2 = 2;
		int result = 0;
		int evenResult = 0;

//		for (int i = 1; i <= 10; i++) {
//			System.out.print(f1 + " ");
//			result = f1 + f2;
//			f1 = f2;
//			f2 = result;
//		}

		while (evenResult <= 4000000) {
			if (f1 % 2 == 0) {
				evenResult = evenResult + f1;
			}
			result = f1 + f2;
			f1 = f2;
			f2 = result;
		}

		System.out.println(result);
		System.out.println(evenResult);

	}

}
